FROM mcr.microsoft.com/dotnet/sdk:9.0


RUN apt-get update && \
    apt-get install -y --no-install-recommends netcat-openbsd && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY *.csproj .
RUN dotnet restore
COPY . .