services:
  frontend:
    build:
      context: ../frontend/netmov-front
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - ../frontend/netmov-front:/app
    networks:
      - movnet-network
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    working_dir: /app
    command: >
      sh -c "dotnet ef database update && dotnet backend.dll"
    depends_on:
      - postdb
    networks:
      - movnet-network
    ports:
      - "5000:8080"
    volumes:
      - ./data-protection:/app/keys
  postdb:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: movnet_user
      POSTGRES_DB: movnet_db
      POSTGRES_PASSWORD: pass123
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - movnet-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - movnet-network

networks:
  movnet-network:
    driver: bridge

volumes:
  pgdata:
